# Generated by Django 2.2 on 2020-11-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20201031_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactandlinks',
            name='link',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='contactandlinks',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
